Hometask 1
badliter/smart-home-2019 pull request #1
Opened 2019-10-10 18:10 UTC by badliter

2019-10-10 21:52 UTC, badliter commented
Баданин Максим

2019-10-13 19:45 UTC, a-ivanov requested changes

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public void Execute() throws IOException {
Методы camelCase

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while (event != null) {
Цикл обработки событий - отдельная responsibility, здесь - нарушение SRP.
Исправьте.

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEvent event = EventCreator.getNextSensorEvent();
EventCreator тоже можно передавать как зависимость в Application

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeReader.java
> +    public SmartHome readHome() throws IOException;
А если мы захотим получать состояние дома через сеть? Здесь детали имплементации видны снаружи, в абстракции (leaky abstraction).
Исправьте.

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandling.java
> +public class EventHandling {
Название *ing больше подходит для пакета. Классы с имплементациями лучше называть существительными.

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandling.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Когда появятся новые типы событий, придется менять этот код. Здесь нарушен OCP.
К тому же этот класс делает слишком много по распределению конкретных типов событий (нарушен SRP).
Исправьте.

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEvent.java
> +                SensorCommand command = new SensorCommand(CommandType.LIGHT_OFF, light.getId());
Сейчас здесь нарушается OCP - при необходимости изменить способа отправки команды придется менять этот код. Лучше вынести часть этой логики в зависимость класса LightEvent.
Исправьте.

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEvent.java
> +    public static void lightTurnOn(Room room, Light light){
Этот метод (как и некоторые другие) используется только внутри этого класса - он не входит в API. Нет необходимости делать его public. А что если его будут вызывать пользователи этого класса (здесь будет в ненужный момент печататься лог)?
Исправьте.

2019-10-13 19:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEvent.java
> +                        closeDoor(room, door);
Здесь нарушен SRP - меняем состояние door и выполняем сценарий умного дома.
Исправьте.

2019-10-22 08:31 UTC, a-ivanov requested changes
Внесите правки в первое задание.

2019-10-22 08:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public void Execute() throws IOException {
Не исправлено.

2019-10-26 18:11 UTC, a-ivanov requested changes
Все поправки по первому дз исправлены в https://github.com/badliter/smart-home-2019/pull/2? Если да, то закройте этот пулл реквест.

2019-10-27 16:40 UTC, closed without merging