hometask-2
badliter/smart-home-2019 pull request #2
Opened 2019-10-17 20:37 UTC by badliter

Баданин Максим

2019-10-26 18:24 UTC, a-ivanov requested changes
Хорошо. По первому дз от меня зачет, по второму надо поправить.

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AllLightTurnOff.java
> +        CommandSender.sendCommand(command);
Как зависимость через конструктор - сейчас нарушен OCP.

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            new EventProcess().processEvent(smartHome, event);
Не надо создавать на каждую итерацию по EventProcess.

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcess.java
> +        new LightEventProcessor().handle(smartHome, event);
Не надо на каждый вызов метода создавать по новому инстансу обработчиков. Их можно настроить один раз в конфигурационной части.

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CheckIsHall.java
> +public class CheckIsHall implements Action {
Подберите более подходящее название: что делает это действие? Только проверяет тип двери?

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    SmartHome getSmartHome();
Зачем внешнему миру получать через Action инстанс SmartHome? Это ответственность Action делать что-то с ним или дургим объектом дома, уберите.

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    Room getRoom();
См. коммент вверху.

2019-10-26 18:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        action.setSmartHome(this);
Объект должен быть передан в Action без сеттеров. С сеттерами любой клиент может подменять дом в действии на другой. Исправьте.

2019-10-29 18:27 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/AllLightTurnOff.java
> +        CommandSender.sendCommand(command);
не понял, какая зависимость?
у SensorCommand?
что значит "Как"?

2019-10-29 18:27 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/AllLightTurnOff.java
> +        CommandSender.sendCommand(command);
> Как зависимость через конструктор - сейчас нарушен OCP.
не понял, какая зависимость?
у SensorCommand?
что значит "Как"?

2019-10-29 21:13 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            new EventProcess().processEvent(smartHome, event);
> Не надо создавать на каждую итерацию по EventProcess.

Добавил коллекцию в классе CollectionEventProcessor, которую создаю в Application
Изменения запушил в hometask-2

2019-10-29 21:14 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/EventProcess.java
> +        new LightEventProcessor().handle(smartHome, event);
> Не надо на каждый вызов метода создавать по новому инстансу обработчиков. Их можно настроить один раз в конфигурационной части.

Добавил коллекцию в классе CollectionEventProcessor, которую создаю в Application
Изменения запушил в hometask-2

2019-10-29 21:14 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            new EventProcess().processEvent(smartHome, event);
> Не надо создавать на каждую итерацию по EventProcess.

Поправил.
Изменения запушил в Изменения запушил в hometask-2.

2019-10-29 21:16 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/CheckIsHall.java
> +public class CheckIsHall implements Action {
> Подберите более подходящее название: что делает это действие? Только проверяет тип двери?

Изменил на HallChecker - проверяет является ли комната холом, если да, то вызывает еще один Action AllLigthTurnOff
Изменения запушил в hometask-2

2019-10-29 21:17 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    SmartHome getSmartHome();
> Зачем внешнему миру получать через Action инстанс SmartHome? Это ответственность Action делать что-то с ним или дургим объектом дома, уберите.

Убрал.
Изменения запушил в hometask-2

2019-10-29 21:17 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    Room getRoom();
> См. коммент вверху.

> См. коммент вверху.

2019-10-29 21:19 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        action.setSmartHome(this);
> Объект должен быть передан в Action без сеттеров. С сеттерами любой клиент может подменять дом в действии на другой. Исправьте.

Убрал.
Теперь в execute я передаю Action и Collection<Actionable> 
Изменения запушил в hometask-2

2019-10-29 21:19 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    Room getRoom();
> См. коммент вверху.

См. коммент вверху.

2019-10-30 09:08 UTC, a-ivanov requested changes
Подумайте над текстом 2го задания еще раз. Задача - уйти от внешней итерации и преместить эту ответственность в объекты дома.

2019-10-30 09:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private void performLoopEventHandle(SmartHome smartHome) {
Вынесите цикл обработки в отдельный класс.

2019-10-30 09:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/WorkWithActionableCollection.java
> +    private Actionable get(Class<?> clazz) {
Задача 2го задания - уйти от внешней явной итерации по объектам дома. Итерация должна выполняться сами объектами через интерфейс Actionable. исправьте.

2019-10-30 09:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/action/OpenDoor.java
> +        Actionable actionable = new WorkWithActionableCollection(collection).getLast();
Вот эта вся логика - то же самое, что было без Actionable. Уберите этот класс и используйте внутренний итератор.

2019-10-30 09:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Actionable.java
> +    void execute(Action action, Collection<Actionable> collection);
Actionalble по заданию работает только над Action для соответствия внутреннему итератору. Исправьте.

2019-10-30 09:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    void act(Collection<Actionable> collection);
Action по заданию действует над одним объектом дома. Исправьте.

2019-11-03 14:23 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private void performLoopEventHandle(SmartHome smartHome) {
> Вынесите цикл обработки в отдельный класс.

>> Внес в класс LoopEventHandler

2019-11-03 14:24 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private void performLoopEventHandle(SmartHome smartHome) {
> Вынесите цикл обработки в отдельный класс.

Внес в класс LoopEventHandler

2019-11-03 14:24 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/home/WorkWithActionableCollection.java
> +    private Actionable get(Class<?> clazz) {
> Задача 2го задания - уйти от внешней явной итерации по объектам дома. Итерация должна выполняться сами объектами через интерфейс Actionable. исправьте.

Исправил

2019-11-03 14:25 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Actionable.java
> +    void execute(Action action, Collection<Actionable> collection);
> Actionalble по заданию работает только над Action для соответствия внутреннему итератору. Исправьте.

Исправил

2019-11-03 14:25 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    void act(Collection<Actionable> collection);
> Action по заданию действует над одним объектом дома. Исправьте.

Исправил

2019-11-04 22:38 UTC, a-ivanov requested changes
По 1му зачет, по 2му - надо доделать немного и будет зачет.

2019-11-04 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
>      public Collection<Room> getRooms() {
Уберите этот метод, используйте внутренний итератор.

2019-11-04 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessor/HallEventProcessor.java
> +        for (Room room : smartHome.getRooms()){
Используйте внутренний итератор.

2019-11-04 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
> +        for (Room room : rooms) {
А дом будет попадать в цикл? Исправьте.

2019-11-04 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home/Room.java
> +        for (Light light : lights) {
А комната будет попадать в цикл? Исправьте.

2019-11-05 19:16 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/home/Room.java
> +        for (Light light : lights) {
> А комната будет попадать в цикл? Исправьте.

исправил

2019-11-05 19:16 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
> +        for (Room room : rooms) {
> А дом будет попадать в цикл? Исправьте.

исправил

2019-11-05 19:17 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/eventprocessor/HallEventProcessor.java
> +        for (Room room : smartHome.getRooms()){
> Используйте внутренний итератор.

теперь используется внутренний итератор

2019-11-05 19:18 UTC, badliter commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
>      public Collection<Room> getRooms() {
> Уберите этот метод, используйте внутренний итератор.

убрал, такой же метод убрал в Room

2019-11-17 14:33 UTC, closed without merging